### ISSUE TITLE
Install halted - Please Help!

### ISSUE THREAD

**Issue by itpastor** [JhumanJ/OpnForm#112]
Hi there!  OpnForm looks great - can't wait to get it running in docker, but I'm having an issue.  I'm seeing the following errorwhen running it: 
 "In Filesystem.php line 254:  
/project/vendor does not exist and could not be created"
see screenshot below:

**_My steps to install:_**
1.  I created an install folder
2. I copied all of the following files into the install folder:
.env.example
.env.docker
.gitignore
Makefile
docker-compose.yml
php-cli.Dockerfile
composer.json

3. installed make   "sudo apt install make -y"
4. Ran "sudo make up"

**Is there another dependency I should install, or another way around this?  Thanks,**

![Install_error_msg](https://user-images.githubusercontent.com/40804331/229218795-bea3e821-370d-4ecd-8de6-befe53f1be0c.png)

**Comment by mrysn** [comment]
I would clone the repo, cd into the directory and then run `sudo make up`

However if you just plan to install and use (and not dev) try this:

1. `git clone https://github.com/JhumanJ/OpnForm.git`
2. `cd OpnForm`
3. `cp .env.docker .env`
4. `docker compose up -d server` ... instead of `sudo make up`

Please let us know how you get on, I am keen to see if it's smooth from there on or if you encounter any issues.

Thanks

**Comment by itpastor** [comment]
Thanks - I tried that, it ran, but the following appeared:
service "migrate" didn't completed successfully: exit 255

Just before that error message it showed:
 ⠿ Container opnform-database-1  Healthy

 ⠿ Container opnform-migrate-1   Exited

 ⠿ Container opnform-server-1    Created

**Comment by mrysn** [comment]
I have just tried a fresh run and am getting the same problem - migrate fails in seconds and the container exits. I think it's still failing to reach the database, but I can't find a way to edit the migrate container settings.

**Comment by itpastor** [comment]
JhumanJ:
I have tried this on 3 different machines (VM's with Docker)  Here are the details of 2 of them:

Machine 1: (Self hosted)
Ubuntu 20.04 (updated with latest patches)
4CPU's
4GB Ram
Docker - v23.0.3
Docker Compose - v2.17.2

Machine 2: (Vultr.com hosted)
Ubuntu 22.10
2CPU
2GB Ram
Docker - v20.10.17
Docker Compose - v2.5.0

**Comment by FlorianB-DE** [comment]
Having the same problem on arm64 if that's helpful

**Comment by pihomeserver** [comment]
Same issue here on a self hosted VPS (4 CPU - 6GB RAM)

**Comment by pihomeserver** [comment]
Solved by replacing user id 1000 with my own user id and group id in docker-compose file and a fresh install 
```
user: '61616:61616'
```
Now the webserver is available and running but another pop up. I will look for an existing issue or open a new one

**Comment by pihomeserver** [comment]
Ok so now it's up and running
I revert back to user 1000 because that's the user id in the node container and another generates errors with npm cache
So to make it up in an unsafe way (i insist !) i created vendor, node_modules, made them writable for all users. Also for bootstrap and public

I guess i should investigate how to map a local folder to a container with a user switch even if the user does not exist on the host

@JhumanJ i guess that user 1000 exists on your server so that's why you don't see the issue ?

**Comment by JhumanJ** [comment]
Hey @pihomeserver, to be transparent I'm not very familiar with docker, hence why the setup is currrently clunky. I'd love to get some help!

**Comment by pihomeserver** [comment]
Sorry i missed the notification

As soon as you set user in docker all commands will be executed with that user id. You mount the local filesystem within the container. The mount maintains the access rights set on the host and that's where the pb raises

Let say my user is 2000. My local file system after the git clone is owned by me so the user 2000
Running the commands in the docker compose will executed by the user 1000 (set up in the compose file) and will create folders and files in the mapped folder. Of course user 1000 does not have sufficient access rights so it falls in error

My stupid trick is to set 777 every where in the mapped folder so user 1000 is free to do what it wants. It works but that's not safe

I guess that your setup is executed by user id 1000 ?

> Hey @pihomeserver, to be transparent I'm not very familiar with docker, hence why the setup is currrently clunky. I'd love to get some help!

**Comment by bastien-naturavelo** [comment]
Hey ! Any update on the subject ? What changes are needed to make the install work without the user switch ?

**Comment by JhumanJ** [comment]
Closing in favor of https://github.com/JhumanJ/OpnForm/issues/146
