### ISSUE TITLE
Docker setup not working

### ISSUE THREAD

**Issue by JhumanJ** [JhumanJ/OpnForm#146]
I'm creating this main issue to avoid duplicated. Please feel free to comment your docker issues below. Note that none of us (working on OpnForm) is very knowledgeable with Docker. We know the setup is broken, but for now we cannot afford to spend the time to fix the setup. 

**If you're experimented with Docker and ideally with Laravel, and you'd like to help, please reach out!**

Closed related issues:
- https://github.com/JhumanJ/OpnForm/issues/112
- https://github.com/JhumanJ/OpnForm/issues/145
- https://github.com/JhumanJ/OpnForm/issues/108

**Comment by JhumanJ** [comment]
Closing in favor of https://github.com/JhumanJ/OpnForm/issues/146

**Comment by HusnRafique** [comment]
https://github.com/JhumanJ/OpnForm/issues/145

**Comment by f-str** [comment]
Hi guys,

At my work, we are currently evaluating whether we will use OpnForm as a self-hosted GDPR and health-data compliant forms solution. Therefore, I have successfully created a custom Dockerfile and deployed the application on an internal Kubernetes cluster. 

I would be happy to help you with the Docker problem, but I have almost no experience with PHP or Laravel, but I do have quite a bit of experience with Docker and Docker Compose. 
If that still works out for you, I would take a closer look at the problem and try to fix it.

**Comment by JhumanJ** [comment]
Hey @f-str, thanks a lot for your proposition. That would be awesome! I'd be happy collaborate and help if I can. 
Could you share you share the dockerfile you already have? Does it use docker-compose? 
Thanks!

**Comment by f-str** [comment]
Yes, here is the dockerfile that I use currently:
```dockerfile
FROM node:latest AS node
FROM php:8.1-cli

COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/bin/node /usr/local/bin/node
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN install-php-extensions gd \
    exif  \
    zip  \
    pdo_pgsql  \
    pgsql  \
    bcmath

ARG APP_NAME
ENV APP_NAME=$APP_NAME
ARG APP_URL=$APP_URL
ENV APP_URL=$APP_URL
ARG APP_DEBUG
ENV APP_DEBUG=$APP_DEBUG
ARG APP_LOG_LEVEL
ENV APP_LOG_LEVEL=$APP_LOG_LEVEL
ARG APP_KEY
ENV APP_KEY=$APP_KEY

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

ARG POSTGRES_HOST
ENV POSTGRES_HOST=$POSTGRES_HOST
ARG POSTGRES_PORT
ENV POSTGRES_PORT=$POSTGRES_PORT
ARG POSTGRES_USERNAME
ENV POSTGRES_USERNAME=$POSTGRES_USERNAME
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ARG POSTGRES_DATABASE
ENV POSTGRES_DATABASE=$POSTGRES_DATABASE
ARG DB_HOST
ENV DB_HOST=$DB_HOST
ARG DB_DATABASE
ENV DB_DATABASE=$DB_DATABASE
ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG DB_PORT
ENV DB_PORT=$DB_PORT
ARG DB_CONNECTION
ENV DB_CONNECTION=$DB_CONNECTION

ARG PORT
ENV PORT=$PORT

ARG GITHUB_TOKEN

ARG MAIL_HOST
ENV MAIL_HOST=$MAIL_HOST
ARG MAIL_PORT
ENV MAIL_PORT=$MAIL_PORT
ARG MAIL_USERNAME
ENV MAIL_USERNAME=$MAIL_USERNAME
ARG MAIL_PASSWORD
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ARG MAIL_ENCRYPTION
ENV MAIL_ENCRYPTION=$MAIL_ENCRYPTION
ARG MAIL_FROM_ADDRESS
ENV MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS

# Allow composer to run with root privileges
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app
COPY /OpnForm .

RUN composer config github-oauth.github.com $GITHUB_TOKEN

# Install PHP dependencies
RUN composer install

# Install nodejs dependencies
RUN npm install

# build nodejs app
RUN npm run build

EXPOSE $PORT

CMD ["sh", "start.sh"]
```
The `start.sh` script has the following content:
```sh
#!/bin/bash

# Run Migrations
php artisan migrate --force

# Start PHP-Application
php -S 0.0.0.0:"$PORT" -t ./public
```
**Note:** this dockerfile is not intended for a production usecase.    
There are a number of improvements which should be done, including:
- do not use the root user
- use a multistage build process with a build and run image to reduce the image size and optimize regarding to caching the individual layers

As I mentioned before, I use the dockerfile to build a image and then deploy it in a Kubernetes environment, so there is no Docker Compose involved.    
I have offloaded the image build process to a CI-Pipeline job, which does basically the following things:
1. clone the OpnForm repo
2. deletes the `composer.lock` file (since there seems to be a dependency conflict)
3. copies the `start.sh` script to the cloned repo directory
4. `docker build` with the dockerfile above with the args which are generated from a .env file
5. `docker login` and `docker push` to store the build image our container image registry

**Comment by JhumanJ** [comment]
Thanks a lot for your help @f-str, in the end @donuk has helped us achieve this 🙌 I'll be merging his PR very soon!

**Comment by JhumanJ** [comment]
Fixed in https://github.com/JhumanJ/OpnForm/pull/153!
