### ISSUE TITLE
Docker and Docker compose

### ISSUE THREAD

**Issue by userbradley** [JhumanJ/OpnForm#50]
Hey!

Would be awesome to have a `Dockerfile` and a `docker-compose.yml`

I know you're still writing the guide on self hosting, but thought I would show interest in a docker setup!

**Comment by JhumanJ** [comment]
Hey Bradley, that's definitely planned! Unfortunately, I have close to zero docker experience. I started to look at it with @cellerich but with the holidays we put this aside for a bit. Would you be available to help with it as well? Thanks!

**Comment by userbradley** [comment]
Woo! Certainly happy to help! 

If you have 18 minutes and 19 seconds to kill, this is the [Youtube Video](https://www.youtube.com/watch?v=SnSH8Ht3MIc) I learnt docker files from!

Happy to give you pointers along the way etc!

If you can get the install on `ubuntu` or similar OS instructions done I can take a stab at a dockerfile!

**Comment by cellerich** [comment]
@netsolid-ca 
> Let me know if you want me to share my docker setup

Would love to see your approach!

**Comment by netsolid-ca** [comment]
[docker-setup.zip](https://github.com/JhumanJ/OpnForm/files/10794620/docker-setup.zip)

Attached are my 2 setups, staging is going up to my gitlab-runner, the other files are for my locally hosted environment.

I  should mention that after starting the machine you'll need to attach to the console (docker exec -it <container-name> /bin/bash) so you can run composer update and npm install.

Finally, with my staging environment I had to add the following line to spa.blade.php in order to resolve the mixed-content message. (All other methods I attempted didn't work. I believe this is because I use traefik for SSL.)
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">

**Comment by cellerich** [comment]
@netsolid-ca 
Thanks for sharing. I will look into it later this week.
Instead of starting the machine and run 'composer update' and 'npm install' you might also look into a "multistage docker build". I found this article useful: [Multistage Docker Build](https://earthly.dev/blog/docker-multistage/)

**Comment by JhumanJ** [comment]
Hey, thanks for sharing your different setup. I've just merged https://github.com/JhumanJ/OpnForm/pull/73 by @philipgatzka, which is a great first step. I'm gonna close this issue for now, please feel free to re-open one or to use discussions.
